["Cash tot. volume",
            "Securities Usable tot. volume",
            "Securities Encumbered tot. volume",
            "Loans tot. volume",
            "Reverse Repos tot. volume",
            "Own Funds tot. volume",
            "Deposits tot. volume",
            "Repos tot. volume",
            "MROs tot. volume",
            "Securities Collateral tot. volume",
            "Securities Reused tot. volume",
            "Av. in-degree",
            "Excess Liquidity",
            "Av. nb. of repo transactions ended",
            "Av. volume of repo transactions ended",
            "Repos av. maturity",
            "Gini",
            "Repos min volume",
            "Repos max volume",
            "Repos av. volume",
            "Assets tot. volume",
            "Collateral reuse",]