[
    "Cash",
    "Securities Usable",
    "Securities Encumbered",
    "Loans",
    "Reverse Repos",
    "Own Funds",
    "Deposits",
    "Repos",
    "MROs",
    "Securities Collateral",
    "Securities Reused",
    "Excess Liquidity",
    "Av. in-degree",
    "Av. out-degree",
    "Nb. of repo transactions ended",
    "Av. volume of repo transactions ended",
    "Repos av. maturity",
]
